//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    public partial class Aplications
    {
        

        [Key]
        public int AplicationID { get; set; }
        [Display(Name = "Imię")]
        public int WorkerID { get; set; }
        [Display(Name = "Start urlopu")]
        public System.DateTime HolidayStart { get; set; }
        [Display(Name = "Koniec urlopu")]
        public System.DateTime HolidayStop { get; set; }
        [Display(Name = "Liczba dni")]
        public int DayOffSum { get; set; }
        [Display(Name = "Dział")]
        public int DepartmentID { get; set; }
        [Display(Name = "Rodzaj urlopu")]
        public string HolidayType { get; set; }
        [Display(Name = "Status")]
        public int StatusID { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Status Status { get; set; }
    }
}
